name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker images
      run: |
        docker compose build --build-arg USER_ID=1000 --build-arg GROUP_ID=1000 web
      
    - name: Run migrations
      run: |
        make migrate
      
    - name: Run Django tests
      run: |
        make test
      
    - name: Clean up
      if: always()
      run: |
        docker compose down -v